// Array of 200 date ideas
const dateIdeas = [
    "Go stargazing at a quiet park.",
    "Take a cooking class together.",
    "Visit a nearby art museum.",
    "Go for a sunset hike.",
    "Have a picnic in the park.",
    "Go to a local farmers' market.",
    "Attend a live concert.",
    "Try a new coffee shop.",
    "Take a scenic drive and stop at random spots.",
    "Go on a bike ride around the city.",
    "Attend a wine tasting event.",
    "Take a pottery or art class together.",
    "Try indoor skydiving.",
    "Watch a sunrise at the beach.",
    "Visit an aquarium.",
    "Go to a comedy show.",
    "Take a day trip to a nearby town.",
    "Try a new type of cuisine.",
    "Take a dance class together.",
    "Have a movie marathon with themed snacks.",
    "Visit a botanical garden.",
    "Go ice skating in the winter.",
    "Take a DIY crafting class.",
    "Do a photo scavenger hunt.",
    "Go to a board game cafe.",
    "Volunteer together at a local shelter.",
    "Visit a haunted house or ghost tour.",
    "Take a pottery painting class.",
    "Go to a rooftop bar and watch the sunset.",
    "Explore a nearby national park.",
    "Go to a local zoo or wildlife reserve.",
    "Visit a planetarium and watch the stars.",
    "Rent a kayak and paddle on the lake.",
    "Take a yoga class together.",
    "Go to a trivia night at a pub.",
    "Do a couples' spa day.",
    "Have a fondue night at home.",
    "Take a painting class together.",
    "Visit a vineyard and have a wine tour.",
    "Go on a hot air balloon ride.",
    "Take a scenic train ride.",
    "Go to a farmer’s market and make a meal with your finds.",
    "Go to a drive-in movie.",
    "Try out an escape room.",
    "Rent a cabin in the woods for the weekend.",
    "Have a themed dinner party at home.",
    "Go to a rooftop restaurant and enjoy dinner.",
    "Take a pottery or ceramic class.",
    "Do a couples’ cooking challenge.",
    "Go to a sushi-making class.",
    "Try zip-lining together.",
    "Have a DIY photo shoot together.",
    "Watch a documentary at home with popcorn.",
    "Go to a local thrift shop and pick out outfits for each other.",
    "Take a pottery painting class.",
    "Rent bikes and explore a new neighborhood.",
    "Attend a local art fair.",
    "Try a new hobby together, like knitting or woodworking.",
    "Plan a surprise date for your partner.",
    "Explore a new neighborhood in your city.",
    "Go camping under the stars.",
    "Go bowling together.",
    "Visit an escape room for a fun challenge.",
    "Take a cooking class together.",
    "Have a picnic in the park with homemade food.",
    "Go on a road trip to a random destination.",
    "Go to a theme park or amusement park.",
    "Take a pottery class together.",
    "Go to a cooking class and learn how to make a new dish.",
    "Try a new type of cuisine you’ve never had before.",
    "Go on a historical walking tour of your city.",
    "Take a scenic boat ride together.",
    "Do a DIY couple’s project.",
    "Have a beach day with a picnic.",
    "Go on a treasure hunt in your city.",
    "Visit a local winery or brewery.",
    "Do a day of volunteering together.",
    "Take a romantic horse-drawn carriage ride.",
    "Visit a local brewery and try new beers.",
    "Take a scenic walk along a nature trail.",
    "Go to an arcade and compete in games.",
    "Rent a tandem bike and explore your area.",
    "Go on a photo walk and snap pictures of interesting things.",
    "Attend a poetry reading at a local cafe.",
    "Do a couple’s workout class together.",
    "Visit a nearby park and take a romantic walk.",
    "Have a movie marathon at home.",
    "Go to a rooftop bar for sunset cocktails.",
    "Take a scenic drive to watch the leaves change in fall.",
    "Go to a historic site or museum.",
    "Try a new sport or outdoor activity together.",
    "Visit a local animal shelter and play with the pets.",
    "Try a DIY craft project together.",
    "Go to a local bakery and try a variety of pastries.",
    "Visit a science museum and try the exhibits.",
    "Take a dance class together.",
    "Have a DIY candle-making night.",
    "Go to a vintage store and find unique items.",
    "Take a pottery or painting class together.",
    "Have a fondue night at home with chocolate and cheese.",
    "Go to an outdoor movie night.",
    "Take a cooking class and learn to make a dish from another country.",
    "Try paddleboarding together.",
    "Go on a fun scavenger hunt in your city.",
    "Go on a hot air balloon ride for a romantic adventure.",
    "Take a scenic boat ride through a river or lake.",
    "Go on a coffee shop hopping adventure.",
    "Take a scenic hike and bring a picnic.",
        "Go to a local farmers market and cook together afterward."
    ];
        "Go stargazing at a quiet park.",
        "Take a cooking class together.",
        "Visit a nearby art museum.",
        "Go for a sunset hike.",
        "Have a picnic in the park.",
        "Go to a local farmers' market.",
        "Attend a live concert.",
        "Try a new coffee shop.",
        "Take a scenic drive and stop at random spots.",
        "Go on a bike ride around the city.",
        "Attend a wine tasting event.",
        "Take a pottery or art class together.",
        "Try indoor skydiving.",
        "Watch a sunrise at the beach.",
        "Visit an aquarium.",
        "Go to a comedy show.",
        "Take a day trip to a nearby town.",
        "Try a new type of cuisine.",
        "Take a dance class together.",
        "Have a movie marathon with themed snacks.",
        "Visit a botanical garden.",
        "Go ice skating in the winter.",
        "Take a DIY crafting class.",
        "Do a photo scavenger hunt.",
        "Go to a board game cafe.",
        "Volunteer together at a local shelter.",
        "Visit a haunted house or ghost tour.",
        "Take a pottery painting class.",
        "Go to a rooftop bar and watch the sunset.",
        "Explore a nearby national park.",
        "Go to a local zoo or wildlife reserve.",
        "Visit a planetarium and watch the stars.",
        "Rent a kayak and paddle on the lake.",
        "Take a yoga class together.",
        "Go to a trivia night at a pub.",
        "Do a couples' spa day.",
        "Have a fondue night at home.",
        "Take a painting class together.",
        "Visit a vineyard and have a wine tour.",
        "Go on a hot air balloon ride.",
        "Take a scenic train ride.",
        "Go to a farmer’s market and make a meal with your finds.",
        "Go to a drive-in movie.",
        "Try out an escape room.",
        "Rent a cabin in the woods for the weekend.",
        "Have a themed dinner party at home.",
        "Go to a rooftop restaurant and enjoy dinner.",
        "Take a pottery or ceramic class.",
        "Do a couples’ cooking challenge.",
        "Go to a sushi-making class.",
        "Try zip-lining together.",
        "Have a DIY photo shoot together.",
        "Watch a documentary at home with popcorn.",
        "Go to a local thrift shop and pick out outfits for each other.",
        "Take a pottery painting class.",
        "Rent bikes and explore a new neighborhood.",
        "Attend a local art fair.",
        "Try a new hobby together, like knitting or woodworking.",
        "Plan a surprise date for your partner.",
        "Explore a new neighborhood in your city.",
        "Go camping under the stars.",
        "Go bowling together.",
        "Visit an escape room for a fun challenge.",
        "Take a cooking class together.",
        "Have a picnic in the park with homemade food.",
        "Go on a road trip to a random destination.",
        "Go to a theme park or amusement park.",
        "Take a pottery class together.",
        "Go to a cooking class and learn how to make a new dish.",
        "Try a new type of cuisine you’ve never had before.",
        "Go on a historical walking tour of your city.",
        "Take a scenic boat ride together.",
        "Do a DIY couple’s project.",
        "Have a beach day with a picnic.",
        "Go on a treasure hunt in your city.",
        "Visit a local winery or brewery.",
        "Do a day of volunteering together.",
        "Take a romantic horse-drawn carriage ride.",
        "Visit a local brewery and try new beers.",
        "Take a scenic walk along a nature trail.",
        "Go to an arcade and compete in games.",
        "Rent a tandem bike and explore your area.",
        "Go on a photo walk and snap pictures of interesting things.",
        "Attend a poetry reading at a local cafe.",
        "Do a couple’s workout class together.",
        "Visit a nearby park and take a romantic walk.",
        "Have a movie marathon at home.",
        "Go to a rooftop bar for sunset cocktails.",
        "Take a scenic drive to watch the leaves change in fall.",
        "Go to a historic site or museum.",
        "Try a new sport or outdoor activity together.",
        "Visit a local animal shelter and play with the pets.",
        "Try a DIY craft project together.",
        "Go to a local bakery and try a variety of pastries.",
        "Visit a science museum and try the exhibits.",
        "Take a dance class together.",
        "Have a DIY candle-making night.",
        "Go to a vintage store and find unique items.",
        "Take a pottery or painting class together.",
        "Have a fondue night at home with chocolate and cheese.",
        "Go to an outdoor movie night.",
        "Take a cooking class and learn to make a dish from another country.",
        "Try paddleboarding together.",
        "Go on a fun scavenger hunt in your city.",
        "Go on a hot air balloon ride for a romantic adventure.",
        "Take a scenic boat ride through a river or lake.",
        "Go on a coffee shop hopping adventure.",
        "Take a scenic hike and bring a picnic.",
        "Go to a local farmers market and cook together afterward.",
    
        // Additional 100 ideas
    
        "Have a DIY pizza night at home.",
        "Go on a helicopter ride together.",
        "Take a day trip to a nearby beach town.",
        "Attend a local theater production.",
        "Go for a night swim under the stars.",
        "Rent a canoe and spend the day on the water.",
        "Take a historical walking tour of your city.",
        "Go to a local ice cream parlor and try unique flavors.",
        "Visit a hidden gem café you’ve never been to.",
        "Create a scrapbook of your relationship together.",
        "Take a photography class together.",
        "Go on a food tour of your city.",
        "Rent a cabin and spend a weekend in the mountains.",
        "Do a home spa day with face masks and relaxation.",
        "Take a pottery wheel class together.",
        "Try a new board game and have a competition.",
        "Explore an abandoned place or building (safely).",
        "Go to a local sports game or match together.",
        "Try rock climbing together at an indoor gym.",
        "Go to a cat café or animal sanctuary.",
        "Take a vintage train ride.",
        "Do a couples’ quiz night at home.",
        "Try a wine and paint night together.",
        "Go to a drive-in theater and watch a retro movie.",
        "Do a DIY tie-dye session at home.",
        "Take a dance class to learn salsa or tango.",
        "Go to a pottery studio and make your own cups.",
        "Have a photo shoot with a professional photographer.",
        "Have a tea party at home with fancy snacks.",
        "Take a scenic drive to find hidden waterfalls.",
        "Go for a hike in the mountains with a picnic.",
        "Visit a rooftop garden or a botanical conservatory.",
        "Go to a local museum and explore new exhibits.",
        "Try a cooking challenge and make a meal with random ingredients.",
        "Go horseback riding on the beach.",
        "Try a sushi-making night at home.",
        "Go to a rooftop lounge and watch the city skyline.",
        "Take a scenic boat tour around a lake or harbor.",
        "Visit a new city or neighborhood you’ve never been to.",
        "Take a pottery class and create your own ceramic pieces.",
        "Spend the day at an amusement park or fair.",
        "Go to a local art gallery and talk about the pieces.",
        "Go ice climbing or rock climbing in the winter.",
        "Take a weekend trip to a nearby cabin or cottage.",
        "Try stand-up paddleboarding at a nearby lake.",
        "Go to a local bakery and try baking cookies together.",
        "Rent a convertible and go on a road trip to the beach.",
        "Take a cooking class to make international dishes.",
        "Attend a local wine and food pairing event.",
        "Go to a hot springs for a relaxing day together.",
        "Make homemade ice cream together.",
        "Go to a concert for a band or artist you both love.",
        "Take a weekend getaway to a cozy Airbnb.",
        "Go horseback riding through scenic trails.",
        "Do a DIY couple’s painting project together.",
        "Take a scenic ferry ride to a nearby island.",
        "Go on a mystery dinner date night.",
        "Take a pottery class and create mugs for each other.",
        "Make vision boards of your future together.",
        "Go to a local brewery and do a beer tasting.",
        "Have a DIY sushi night at home.",
        "Do a couples’ volunteer day for a good cause.",
        "Take a hot air balloon ride together.",
        "Go on a botanical garden tour and take photos.",
        "Try an outdoor yoga class together.",
        "Have a vintage shopping spree at a local thrift store.",
        "Go on a spontaneous adventure and make it a surprise date.",
        "Visit a historical landmark you’ve never seen before.",
        "Go to a farmer’s market and create a farm-to-table dinner.",
        "Attend a local street food festival.",
        "Go on a scenic bike ride along a river.",
        "Take a trip to a local vineyard for a wine-tasting session.",
        "Go to a pumpkin patch or orchard in the fall.",
        "Have a cozy movie marathon with classic films."    

// Function to get a random date idea
function generateDateIdea() {
    const randomIndex = Math.floor(Math.random() * dateIdeas.length);
    document.getElementById('date-idea').textContent = dateIdeas[randomIndex];
}

// Event listener for button click
document.getElementById('generate-btn').addEventListener('click', generateDateIdea);
