const truthQuestions = [
    "What's your biggest fear?",
    "Have you ever lied to get out of trouble?",
    "Who is your secret crush?",
    "What's the most embarrassing thing you've ever done?",
    "Have you ever cheated on someone?",
    "What's the most awkward thing that's ever happened to you on a date?",
    "Who was your first kiss?",
    "Have you ever stolen anything?",
    "What's a bad habit you're trying to break?",
    "What’s the biggest secret you’ve kept from your best friend?",
    "If you could switch lives with anyone for a day, who would it be and why?",
    "What’s the most embarrassing thing you’ve ever posted on social media?",
    "Who do you trust the most in your life?",
    "Have you ever had a crush on someone your friend was dating?",
    "What’s one thing you regret doing in your past?",
    "If you could go back in time, what would you change?",
    "What’s something you're self-conscious about?",
    "Who was your first celebrity crush?",
    "Have you ever made a fake social media account?",
    "If you could know one thing about your future, what would it be?",
    "What’s the worst date you’ve ever been on?",
    "Have you ever had a secret relationship?",
    "What’s the most rebellious thing you’ve ever done?",
    "Have you ever been caught doing something you shouldn’t?",
    "What’s the best compliment you’ve ever received?",
    "Have you ever gotten into a physical fight?",
    "What’s something that always makes you laugh?",
    "Have you ever had a crush on a teacher or boss?",
    "If you could marry a celebrity, who would it be?",
    "What’s something you’ve never told your parents?",
    "Who’s the most famous person you’ve met?",
    "What’s something you’ve never told your siblings?",
    "What’s one thing you’ve always wanted to do but never have?",
    "Have you ever been in love?",
    "What’s the most expensive thing you’ve ever bought?",
    "Have you ever kept a secret for someone else?",
    "What’s the most awkward thing you've said in front of someone?",
    "If you could live anywhere in the world, where would it be?",
    "What’s something you’ve done that you would never tell your parents?",
    "What’s the most embarrassing thing you’ve ever done at work or school?",
    "If you could have dinner with any historical figure, who would it be?",
    "What’s the most scandalous thing you’ve ever done?",
    "If you could date any fictional character, who would it be?",
    "What’s one thing you wish you could change about yourself?",
    "What’s the most spontaneous thing you’ve ever done?",
    "Have you ever lied about your relationship status?",
    "If you had to pick one person to be stuck on a deserted island with, who would it be?",
    "What’s the most adventurous thing you’ve ever done?",
    "What’s the one thing you can’t live without?",
    "If you could trade places with anyone for a week, who would it be?",
    "What’s your biggest insecurity?",
    "What’s the most ridiculous thing you’ve bought?",
    "What’s the most embarrassing song on your playlist?",
    "Have you ever made a huge mistake at work or school?",
    "What’s the most childish thing you still do?",
    "What’s something you’ve been too scared to try?",
    "What’s the most embarrassing thing you’ve ever said to someone you like?",
    "If you could change one thing about your life right now, what would it be?",
    "What’s the craziest thing you’ve done on a dare?",
    "If you could be invisible for a day, what would you do?",
    "What’s the most ridiculous rumor you’ve ever heard about yourself?",
    "What’s the most embarrassing moment you’ve had in front of your crush?",
    "What’s the most unusual thing you’re afraid of?",
    "Have you ever embarrassed yourself in front of a celebrity?",
    "What’s the biggest lie you’ve told to get out of a situation?",
    "If you could swap bodies with anyone in this room for 24 hours, who would it be?",
    "What’s something you’re obsessed with but would never admit?",
    "What’s the weirdest thing you've ever done for money?",
    "What’s the longest you’ve gone without talking to your best friend?",
    "What’s the weirdest food you’ve ever tried?",
    "What’s the best piece of advice you’ve ever received?",
    "What’s one thing you hate but everyone else seems to love?",
    "Have you ever had a crush on someone you shouldn't have?",
    "What’s the most embarrassing thing you've done while drunk?",
    "If you could change your name, what would you change it to?",
    "What’s one thing you've never told anyone because you were too embarrassed?",
    "What’s your biggest turn-off in a relationship?",
    "Have you ever snuck into somewhere you weren’t supposed to?",
    "If you could change one thing about your past, what would it be?",
    "What’s something you’ve never told your best friend?",
    "What’s the most embarrassing thing you’ve done for attention?",
    "What’s the most awkward thing you've done at a party?",
    "What’s something that always makes you feel better when you're sad?",
    "What’s the most extreme thing you’ve ever done to impress someone?",
    "Have you ever had a crush on a fictional character?",
    "What’s the biggest secret you've kept from your family?",
    "What’s the most embarrassing thing you’ve ever done in front of your parents?",
    "Have you ever lied to someone to protect their feelings?",
    "What’s the most awkward conversation you’ve had with a stranger?",
    "Have you ever been caught in a lie?",
    "What’s the most embarrassing thing you’ve done in front of a teacher?",
    "Have you ever sabotaged someone else's relationship?",
    "What’s something you wish you could forget?",
    "Have you ever had a crush on someone in this room?",
    "What’s something you do that no one else knows about?",
    "What’s something you’ve never told anyone about your childhood?",
    "What’s the most embarrassing text message you've sent?",
    "Have you ever kept a secret from your best friend?",
    "What’s the weirdest thing you’ve Googled?",
    "What’s the one thing you would never do for money?",
    "Have you ever done something just to get attention?",
    "What’s the most outrageous lie you’ve ever told?",
    "Have you ever kissed someone you didn’t like?",
    "What’s something you wish you could change about your appearance?",
    "What’s the best prank you’ve ever pulled on someone?",
    "What’s something you would never do on a date?",
    "What’s the most embarrassing thing you’ve done in front of a group?",
    "Have you ever made a wish that actually came true?",
    "What’s something you would never admit to your friends?",
    "Have you ever laughed at something you shouldn’t have?",
    "What’s the worst thing you’ve done to get out of doing something you didn’t want to?",
    "What’s the most shocking thing you’ve heard someone say?",
    "Have you ever broken a promise to someone?",
    "What’s the craziest thing you’ve done on a vacation?",
    "What’s the most embarrassing thing you’ve done in front of your family?",
    "What’s the worst haircut you’ve ever had?",
    "What’s the most unusual place you've ever fallen asleep?",
    "What’s the most surprising thing someone has ever said about you?",
    "What’s one thing you’ve done that you never want anyone to know?",
    "What’s the worst decision you’ve ever made on impulse?",
    "What’s something you’ve always wanted to do but never had the chance?",
    "What’s the funniest thing that’s ever happened to you on a trip?",
    "Have you ever accidentally hurt someone’s feelings?",
    "What’s the worst gift you've ever given someone?",
    "Have you ever sent a text to the wrong person?",
    "What’s something you’re scared of but don’t talk about?",
    "What’s the biggest risk you’ve ever taken?",
    "What’s one thing you always do to calm down?",
    "What’s the most ridiculous thing you've believed as a child?",
    "What’s something you’ve always wanted to tell someone but never did?",
    "What’s one thing you can’t stand about people?",
    "What’s something you’re afraid to admit about yourself?",
    "What’s the most embarrassing fashion choice you've ever made?",
    "What’s something you regret doing in high school?",
    "What’s the biggest thing you’ve learned about yourself in the last year?"
];
const dareActions = [
    "Do 20 pushups.",
    "Dance for 1 minute without stopping.",
    "Sing the chorus of your favorite song out loud.",
    "Let someone write a word on your forehead with a marker.",
    "Post an embarrassing photo of yourself on social media.",
    "Do your best impression of a celebrity of your choice.",
    "Run around the room 10 times.",
    "Imitate an animal of someone else’s choosing for 1 minute.",
    "Act like a baby for 2 minutes.",
    "Speak in an accent of someone else’s choosing for the next 5 minutes.",
    "Do your best chicken dance outside on the lawn.",
    "Let the group send a text message from your phone to someone.",
    "Wear socks on your hands for the next 10 minutes.",
    "Give someone your phone and let them send a text to anyone in your contact list.",
    "Wear your clothes backwards for the next 10 minutes.",
    "Do your best impression of a robot for 2 minutes.",
    "Imitate someone in the room until someone guesses who it is.",
    "Eat a spoonful of mustard.",
    "Do 10 jumping jacks.",
    "Pretend to be a waiter/waitress and take snack orders from everyone.",
    "Let someone draw on your face with a marker.",
    "Post something embarrassing on social media and leave it up for an hour.",
    "Do a cartwheel.",
    "Speak in rhymes for the next 10 minutes.",
    "Try to lick your elbow.",
    "Take a silly selfie and send it to someone.",
    "Dance like nobody's watching for 2 minutes.",
    "Try to touch your toes without bending your knees.",
    "Do your best impression of a baby crying.",
    "Eat a slice of lemon without making a face.",
    "Pretend you’re a model and do a 30-second runway walk.", 
    "Do your best impression of a famous singer.",
    "Let someone else pick a song for you to dance to.",
    "Try to juggle 3 items for 1 minute.",
    "Do 15 squats in a row.",
    "Talk in a high-pitched voice for the next 10 minutes.",
    "Let someone give you a makeover using whatever they find.",
    "Try to touch your toes for 1 minute without stopping.",
    "Imitate your favorite movie scene for 2 minutes.",
    "Call a friend and sing Happy Birthday to them.",
    "Walk around the room with a pillow on your head for 5 minutes.",
    "Do 10 sit-ups in a row.",
    "Imitate a famous comedian for 2 minutes.",
    "Do a dramatic reading of a random text message.",
    "Speak in only questions for the next 5 minutes.",
    "Let someone else write a message on your hand.",
    "Wear sunglasses for the next 10 minutes, even indoors.",
    "Post a video of you doing something silly on your social media.",
    "Pretend to be a waiter/waitress and serve drinks to everyone.",
    "Do an impression of your favorite character from a movie.",
    "Send a funny meme to someone in your contacts list.",
    "Eat a raw onion slice.",
    "Give someone a compliment every minute for 5 minutes.",
    "Wear your shirt inside out for the rest of the game.",
    "Pretend to be a statue and stand still for 2 minutes.",
    "Imitate a family member for 1 minute.",
    "Call someone and sing a random song to them.",
    "Do 10 push-ups with a twist (do them while clapping in between).",
    "Pretend to be a pet for 2 minutes.",
    "Do a dramatic monologue from your favorite movie.",
    "Try to hula hoop for 1 minute.",
    "Let someone else choose your outfit for the next 10 minutes.",
    "Speak only in song lyrics for the next 5 minutes.",
    "Act like you’re on a talk show and interview someone.",
    "Imitate a baby crying for 1 minute.",
    "Try to walk around the room with your eyes closed for 1 minute.",
    "Do your best dance move for 2 minutes.",
    "Try to make a sandwich with your eyes closed.",
    "Do 10 jumping jacks while singing your favorite song.",
    "Pretend you’re a news anchor and announce something random.",
    "Imitate a famous TV character for 1 minute.",
    "Try to do a split.",
    "Speak in the third person for the next 5 minutes.",
    "Do 20 sit-ups while holding a heavy object.",
    "Try to stand on one leg for 1 minute.",
    "Pretend to be a waiter and serve pretend food to everyone.",
    "Talk in a low voice for the next 10 minutes.",
    "Do a silly walk for 1 minute.",
    "Take a video of yourself dancing and send it to a friend.",
    "Pretend you’re a superhero for 5 minutes.",
    "Do your best dance move and hold it for 30 seconds.",
    "Imitate someone else in the room for 2 minutes.",
    "Pretend you’re a famous singer and perform a concert.",
    "Do an impression of your favorite animal for 2 minutes.",
    "Try to balance something on your head for 2 minutes.",
    "Do your best impression of a famous character from a movie.",
    "Run around the room in circles for 1 minute.",
    "Pretend to be a robot for 2 minutes.",
    "Do 5 cartwheels in a row.",
    "Imitate an animal for 1 minute.",
    "Let someone give you a funny nickname for the next 10 minutes.",
    "Try to make someone laugh without saying a word.",
    "Run in place for 1 minute while singing a song.",
    "Act like you’re on a cooking show and explain how to make a sandwich.",
    "Talk in a whisper for the next 5 minutes.",
    "Pretend you’re a cheerleader and do a cheer.",
    "Post a video of yourself doing something silly and tag a friend.",
    "Do 10 jumping jacks and shout a random phrase each time.",
    "Imitate someone’s voice in the room for 2 minutes.",
    "Do 10 pushups with a twist (cross your arms between each pushup).",
    "Walk backward for 2 minutes.",
    "Do 10 lunges with a funny face.",
    "Act like a character from a TV show for 3 minutes.",
    "Pretend to be a rock star and do a mini performance.",
    "Do your best impression of a robot.",
    "Dance like nobody’s watching for 1 minute.",
    "Call someone and sing the alphabet song to them.",
    "Do 15 squats while holding a pillow above your head.",
    "Pretend to be a model and do a 30-second runway walk.",
    "Speak in a monotone voice for the next 5 minutes.",
    "Pretend you’re in a commercial and sell a random item.",
    "Do an impression of someone you know for 2 minutes.",
    "Post a photo with a funny filter and send it to your friend.",
    "Do your best impression of a famous comedian.",
    "Run outside and shout a random phrase.",
    "Act like you’re getting interviewed for a documentary.",
    "Do 10 push-ups while humming your favorite song.",
    "Pretend to be a tourist and give a tour of the room.",
    "Talk like a pirate for the next 5 minutes.",
    "Pretend to be a baby and crawl on all fours for 1 minute.",
    "Try to balance a spoon on your nose for 1 minute.",
    "Sing your favorite song in a silly voice.",
    "Act like a superhero and strike a pose.",
    "Pretend to be a teacher and explain something random.",
    "Do a cartwheel or roll on the floor.",
    "Imitate someone’s laugh for 1 minute.",
    "Walk around the room pretending to be in slow motion.",
    "Let someone else dress you up in silly clothes.",
    "Do 10 burpees.",
    "Try to do a handstand for 1 minute.",
    "Do 20 sit-ups while singing a song.",
    "Pretend to be a character from your favorite show.",
    "Do 10 jumping jacks while saying your favorite movie quotes.",
    "Imitate a famous movie scene and act it out.",
    "Talk in rhymes for the next 5 minutes.",
    "Pretend you’re in a scary movie and scream.",
    "Pretend to be an animal of someone’s choice for 2 minutes.",
    "Make a silly face and hold it for 1 minute.",
    "Do 10 squats while singing your favorite song.",
    "Do your best dance move for 1 minute and hold it.",
    "Pretend you’re a professional wrestler and perform an entrance.",
    "Imitate a famous singer for 2 minutes.",
    "Call someone and sing a random song to them.",
    "Do 10 pushups and shout out a funny phrase with each one."
];

document.getElementById("truth-btn").addEventListener("click", function() {
    const randomTruth = truthQuestions[Math.floor(Math.random() * truthQuestions.length)];
    document.getElementById("question").textContent = randomTruth;
    document.getElementById("new-game").classList.remove("hidden");
});

document.getElementById("dare-btn").addEventListener("click", function() {
    const randomDare = dareActions[Math.floor(Math.random() * dareActions.length)];
    document.getElementById("question").textContent = randomDare;
    document.getElementById("new-game").classList.remove("hidden");
});

document.getElementById("new-game").addEventListener("click", function() {
    document.getElementById("question").textContent = "Press a button to start the game!";
    this.classList.add("hidden");
});
